version: '3.4'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - './:/app'
    ports:
      - 9000:9000

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: cardinal
      POSTGRES_USER: cardinal
      POSTGRES_DATABASE: cardinal
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: 'galkaev'

volumes:
  dbdata: {}
