version: "3.4"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - "./:/app"

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1337H4xx0rz"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: {}
