name: Docker

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:
  build_push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: hbjydev/cardinal/cardinal
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
