name: Release Builds

on:
  push:
    tags: ["*"]

jobs:
  build_push_t:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cardinal:${{ steps.get_version.outputs.SOURCE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/cardinal:latest
            ghcr.io/${{ github.repository_owner }}/cardinal:${{ steps.get_version.outputs.SOURCE_TAG }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Updated Kubernetes deployment image
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: set image deployments/cardinal-bot cardinal=${{ steps.get_version.outputs.SOURCE_TAG }}
